version: '3'
tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
  test:
    desc: Run tests and generate coverage report
    cmds:
      - mkdir -p coverage
      - go test ./... -coverprofile=coverage/coverage.out
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html